### ISSUE TITLE
srvdir.net certificate has expired

### ISSUE THREAD

**Issue by davidmz** [inconshreveable/srvdir#13]
*.srvdir.net certificate has expired on 2015-12-15. Please, update it.

**Comment by avdaredevil** [comment]
Yes, please all automation download tools relying on this library have started to fail!

**Comment by psvanstrom** [comment]
Any news on this? Should be quick to fix. Use letsencrypt.org to issue a new certificate if there's some problem with the current CA.

**Comment by davidsturgeon** [comment]
Looks like the site is not longer supported. [https://twitter.com/dsturgeo/status/715937538075131905](https://twitter.com/dsturgeo/status/715937538075131905) I suppose you could still just set up your version on your own domain with the server code in the repo.

**Comment by inconshreveable** [comment]
website is updated to communicate that the service is no longer available. i'll update the README shortly as well
